### PR TITLE
fix: interpolate page# in pageNumber label

### PR DESCRIPTION
**Pull request by louis-bompart**
https://coveord.atlassian.net/browse/KIT-3333

### CODE REVIEW

**Review by fbeaudoincoveo — APPROVED** [review]

**Comment by louis-bompart** [comment]
> I don't understand this change. It looks like it works correctly in master. I see `Page 1` , `Page 2` ,` Page 3` and more.

Check the `aria-label` attributes ;)

**Comment by alexprudhomme** [comment]
> > I don't understand this change. It looks like it works correctly in master. I see `Page 1` , `Page 2` ,` Page 3` and more.
> 
> Check the `aria-label` attributes ;)

This is in master @louis-bompart 

image

**Comment by louis-bompart** [comment]
> > > I don't understand this change. It looks like it works correctly in master. I see `Page 1` , `Page 2` ,` Page 3` and more.
> > 
> > 
> > Check the `aria-label` attributes ;)
> 
> This is in master @louis-bompart
> 
> image

Check on https://stackblitz.com/edit/atomicv2?file=index.html
Flush your build/cache maybe? I don't reproduce on master on my machine
`git switch -f master ; git clean -xfd ; npm i ; npm start -w=@coveo/atomic`

**Review by alexprudhomme — APPROVED** [review]
I see it now must have been the cache. Thank you :)

**Review by olamothe — APPROVED** [review]

**Pull request merged**
