### PR TITLE
chore: revert add auto-label for v2 PRs (#4505)

### PR DESCRIPTION
**Pull request by alexprudhomme**
This reverts commit 2e1ffe8cbb04a38844c7711412290f721625774a.
https://coveord.atlassian.net/browse/KIT-3661

### CODE REVIEW

**Review by fbeaudoincoveo — APPROVED** [review]

**Review by louis-bompart — CHANGES_REQUESTED** [review]
Workflow is disabled let's fix instead

**Comment by alexprudhomme** [comment]
> Workflow is disabled let's fix instead

@louis-bompart  This action should not be in the `master` branch. It should be in `v2`. We can't fix it here. Every PR based on `v2` won't have access to that action...

**Comment by louis-bompart** [comment]
> > Workflow is disabled let's fix instead
> 
> @louis-bompart  This action should not be in the `master` branch. It should be in `v2`. We can't fix it here. Every PR based on `v2` won't have access to that action...

I don't think so.
I think instead this is due to 
> To ensure repository security, branches with names that match certain patterns (such as those which look similar to SHAs) may not trigger workflows with the pull_request_target event.
From https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

**Comment by alexprudhomme** [comment]
> > > Workflow is disabled let's fix instead
> > 
> > 
> > @louis-bompart  This action should not be in the `master` branch. It should be in `v2`. We can't fix it here. Every PR based on `v2` won't have access to that action...
> 
> I don't think so. I think instead this is due to
> 
> > To ensure repository security, branches with names that match certain patterns (such as those which look similar to SHAs) may not trigger workflows with the pull_request_target event.
> > From https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

proof it does not work. the v2 branch has no access to that action. https://github.com/coveo/ui-kit/pull/4544

**Pull request closed without merging**
