### PR TITLE
feat(quantic)!: initial value for the originLevel3 updated to be a valid value

### PR DESCRIPTION
**Pull request by mmitiche**
[SFINT-5663](https://coveord.atlassian.net/browse/SFINT-5663)

- By doing this we are making sure that the value of the origin level 3, aka the referrer, is set to a valid value which is ideally the url of the page from where the Quantic page is initialized. 

https://github.com/user-attachments/assets/a3c88f4a-21f8-4d18-9eb9-9f02c5229690

[SFINT-5663]: https://coveord.atlassian.net/browse/SFINT-5663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SimonMilord — APPROVED** [review]
Looks fine to me, but why are we adding that? Could you shed more light on the why please? :)

**Comment by mmitiche** [comment]
> Looks fine to me, but why are we adding that? Could you shed more light on the why please? :)

this is to make sure that default value in headless is not used, cause this value is default which is considered an invalid value by the analytics schemas.

the originLevel3(referrer) needs to be a valid url or an empty string.

**Review by erocheleau — APPROVED** [review]
Just to be sure, are you supposed to set `''` or specifically something like `null` ?

But all good otherwise

**Comment by mmitiche** [comment]
> Just to be sure, are you supposed to set `''` or specifically something like `null` ?
> 
> But all good otherwise

`null` will not work, this only accepts strings.

**Review by fbeaudoincoveo — APPROVED** [review]

**Pull request merged**
