### PR TITLE
docs(headless): tag helpers for doc site generation

### PR DESCRIPTION
**Pull request by kaitlynkatz**
In order to collect all the "others" (types, helpers, interfaces, enums, result templates) during the doc site generation, I've tagged each "other" thing with one of the following tags:
`@docsection = ['Result Templates Manager', 'Result Templates Helpers', 'Result Templates Types and Interfaces', 'Functions', 'Types', 'Interfaces', 'Enums']`

Although it is true that this will also show up in intellisense, the idea is that this can also be helpful to the user by guiding them to the right spot in the reference documentation.

Going forward, any time you add a new "other" that you'd like to appear in the reference documentation, all you have to do is add the appropriate tag (e.g., `@docsection Types`) to the typedoc annotation.

I've added the appropriate tag to everything I saw exported in the main index.ts file; if there are any others that need to be documented, please let me know or feel free to check out the branch and add them yourself.

### CODE REVIEW

**Comment by samisayegh** [comment]
I would need more context on how these tags will be used and laid out in the docs, but here are some thoughts:

1. Assuming everything with `@docsection <key>` is grouped on the same doc page, would that be a useful page? There would be many unrelated things so, is it really best to group them together with a tag?

2. I view the `@docsection` tags as a documentation site concern and detail, that would ideally not be mixed with headless code. If the doc team wants to change the layout in the future, then adjusting the tags in headless will only affect the next published version's layout. Previous versions will continue to use the old layout.

Instead, I think it makes more sense for layout and categorization to occur in the doc code base. After extracting the JSON from headless, you would divide things up as desired,

**Comment by ThibodeauJF** [comment]
Yes people using the Headless library directly would see this piece of typedoc and not know what it should mean, it is more internal than external.

**Comment by kaitlynkatz** [comment]
The problem we're having is that there's just no other feasible way to _locate_ exactly what we're extracting. Originally, we had relied on the folder and file structure, but as that becomes more complex, there's just no other way to tell exactly what types/interfaces/helpers etc need to be documented. Even with controllers, now that the options are in a different file we are having trouble finding them.

> Assuming everything with @docsection <key> is grouped on the same doc page, would that be a useful page? There would be many unrelated things so, is it really best to group them together with a tag?

It's true that this strategy groups entities together by whether it's a type, interface, etc. If your team has a different vision for how everything should be organized, we should discuss that asap.

So, I think it would be a good idea to have a meeting to discuss all of these points. Let me know who I should talk to and we can set something up.

**Comment by btaillon** [comment]
Correct me if I'm wrong, but it looks like the structure of `headless` is more indicative of what needs to be documented.
* Controllers (`/controllers`)
* Actions (`/features`)

**Comment by btaillon** [comment]
Woops, accidentally closed the PR when trying to cancel a comment, my bad.

**Comment by olamothe** [comment]
>  There's just no other way to tell exactly what types/interfaces/helpers etc need to be documented. Even with controllers, now that the options are in a different file we are having trouble finding them.

If that's the main thing we are trying to resolve, the best way I would propose is this: 

1- You try to build something with headless. Like, an actual search page.
2- You start importing functions, types, options, interface etc, in order to achieve your end goal.
3- You look at the JSDoc that you get, from vscode, or from the website.
4- Is the doc clear ? Is something badly documented ? Is something missing ?
5- If something is missing, we document it.
6- Rinse and repeat above steps until "everything" is covered.

Does that make sense ? In the same manner that you would document an interface in the admin UI, you would have to first use it to understand how it works, and then figure out what needs to be documented, and how. The same concepts applies for headless, just that it's code that you use, not a point and click interface.

And if you have problems finding where a type is derived from, you can poke us and we will guide you.

If the problem you are trying to solve is different (eg: the grouping aspect is important for other reasons), please schedule a quick meeting with everybody that commented on this PR. We can re-discuss it live.

**Comment by kaitlynkatz** [comment]
Closing this pull request because Sami and I have brainstormed a better way to do the whole reference doc generation. I'll open a new PR when it's ready.

**Pull request closed without merging**
