### PR TITLE
fix(quantic): Issue where recent queries and suggestions were bold when user hadn't typed anything yet

### PR DESCRIPTION
**Pull request by SimonMilord**
[SFINT-5601](https://coveord.atlassian.net/browse/SFINT-5601)

### ISSUE:
- The current set of options in the `quanticSearchBox` and `quanticStandaloneSearchBox` was `notMatchDelimiters`, so it would bold everything that was not the query instead of the other way around. As you typed, it would "un-bold" the recent queries or the suggestions.
- The logic in the recentQueriesUtils was reflecting the same behaviour.

### SOLUTION PROPOSED:
- Instead of using `notMatchDelimiters` for the bolding, I replaced it with `exactMatchDelimiters` option so that whatever the user type that matches either a suggestion or a recent query is bolded. 
- I also adjusted the logic in the recentQueriesUtils to reflect that desired behaviour.

### Why this solution: 
- It is simple (doesn't add to the complexity), doesn't break the rest of the searchbox logic & tests and achieves the desired behaviour.

## DEMO:

https://github.com/user-attachments/assets/68a238ec-0eaf-4abe-9f78-1a957530790d

[SFINT-5601]: https://coveord.atlassian.net/browse/SFINT-5601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mmitiche** [comment]
The goal is to bold the completions and not the part already wrote by the user.
that's what we have in Quantic and in Atomic.

Atomic behviour:

https://github.com/user-attachments/assets/282e50e4-3ea0-4e8f-bfcb-cad7219f9dce




The issue that was highlighted in this Ticket was that before writing any thing, all the query suggestion was in bold.
IMO, this doesn't really seem like a problem.

In Quantic:
before writing, all the suggestion is in bold. After starting to write the Query, only the completion is in bold.

In Atomic: 
before writing, nothing is in bold. After starting to write the Query, only the completion is in bold.


So the behaviour of after starting writing the query should not change, thus we should revert the changes related to this in this PR.

The issue is what should be the natural behaviour before starting to write the query.
Personally I feel is what we have in Quantic x) as it is logical,  but I can be wrong.

how do you feel it @SimonMilord ?
You can share this question to UX and they should be able to tell us what's more natural.

**Comment by mmitiche** [comment]
Apparently, the search box of `Amazon` and `Youtube` follows the `Quantic` Logic so I think this is an `Atomic` issue.

**Review by erocheleau — APPROVED** [review]

**Comment by erocheleau** [comment]
> Apparently, the search box of `Amazon` and `Youtube` follows the `Quantic` Logic so I think this is an `Atomic` issue.

Wait I missed the discussion on that :D 

So basically the only issue is that the text is in bold when you open the suggestions without any written in it?

And `Amazon` and `YouTube` do the same thing? Everything is in bold before you type anything?

If that's the case then, sorry @SimonMilord but we'll reject this along with the ticket :| 
It doesn't really make sense to change the behavior unless we have a good reason to do so.

**Comment by SimonMilord** [comment]
> > Apparently, the search box of `Amazon` and `Youtube` follows the `Quantic` Logic so I think this is an `Atomic` issue.
> 
> Wait I missed the discussion on that :D
> 
> So basically the only issue is that the text is in bold when you open the suggestions without any written in it?
> 
> And `Amazon` and `YouTube` do the same thing? Everything is in bold before you type anything?
> 
> If that's the case then, sorry @SimonMilord but we'll reject this along with the ticket :| It doesn't really make sense to change the behavior unless we have a good reason to do so.

yup, spoke with @johnnyCoveo, we agreed to leave it as is and close this

**Pull request closed without merging**
