### PR TITLE
feat(quantic): Exposed the headless recommendations scripts in coveoHeadless static resources

### PR DESCRIPTION
**Pull request by SimonMilord**
[SFINT-4832](https://coveord.atlassian.net/browse/SFINT-4832)

Following this [discussion](https://discuss.coveo.com/t/include-recommendations-into-quantic-resources/9196), exposed the headless recommendation engine to coveoheadless static resources in quantic.

[SFINT-4832]: https://coveord.atlassian.net/browse/SFINT-4832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by erocheleau** [comment]
Were you able to try it Simon?
Maybe a screenshot of the CoveoHeadless.buildRecommendation that's exposed in the console after loading Quantic in the local dev server?

**Review by erocheleau — APPROVED** [review]
Everything looks good, but please post a proof that it is really accessible :D

**Review by nathanlb — APPROVED** [review]
Looks like the way to do it :+1:

**Review by mmitiche — APPROVED** [review]
👌

**Comment by SimonMilord** [comment]
> Everything looks good, but please post a proof that it is really accessible :D


🥳 🥳 🥳 
image

**Pull request merged**
