### PR TITLE
feat(quantic)!: toggle on/off feature removed from Quantic RGA component

### PR DESCRIPTION
**Pull request by mmitiche**
[SFINT-5538](https://coveord.atlassian.net/browse/SFINT-5538)

- Toggle ON/OFF removed from the Quantic RGA component.

[SFINT-5538]: https://coveord.atlassian.net/browse/SFINT-5538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by erocheleau — APPROVED** [review]
We'll see if that's true...

> When a package developer removes an Aura or Lightning web component from a package, the component remains in a subscriber’s org after they install the upgraded package. The administrator of the subscriber’s org can delete the component, if desired. This behavior is the same for a Lightning web component or an Aura component with a public or global access value.

> Removing components from managed 1GP or 2GP packages requires approval from Salesforce. To request access to the component removal feature, log a support case in the [Salesforce Partner Community](https://partners.salesforce.com/partnerSupport).

Can you try to generate a package @mmitiche before and after those changes? You can use 2gp for now.

**Comment by mmitiche** [comment]
> We'll see if that's true...
> 
> > When a package developer removes an Aura or Lightning web component from a package, the component remains in a subscriber’s org after they install the upgraded package. The administrator of the subscriber’s org can delete the component, if desired. This behavior is the same for a Lightning web component or an Aura component with a public or global access value.
> 
> > Removing components from managed 1GP or 2GP packages requires approval from Salesforce. To request access to the component removal feature, log a support case in the [Salesforce Partner Community](https://partners.salesforce.com/partnerSupport).
> 
> Can you try to generate a package @mmitiche before and after those changes? You can use 2gp for now.

Will do and report 👍 we will use the same investigation for the Quantic badge component.

**Review by SimonMilord — APPROVED** [review]
👌

**Comment by mmitiche** [comment]
Holding off, we may keep it in v3.

**Pull request closed without merging**
