### PR TITLE
test(quantic): move e2e tests in matrixes

### PR DESCRIPTION
**Pull request by ThibodeauJF**
https://coveord.atlassian.net/browse/KIT-2065

This will cut down the time the build takes to run, and make retries easier.

1 split the tests in 4 spec folders containing about the same length of testing time
- default-1
- default-2
- facets-1
- facets-2

### CODE REVIEW

**Comment by nathanlb** [comment]
Was there a specific logic employed in splitting things into either *-1 or *-2 ?

**Comment by ThibodeauJF** [comment]
No, I lacked creativity here, just took tests that totalled about 5min test time, feel free to rearrange them as needed.

**Comment by nathanlb** [comment]
> No, I lacked creativity here, just took tests that totalled about 5min test time, feel free to rearrange them as needed.

I don't see an obviously better pattern and the goal is strictly to cut the time down so your arrangement makes sense.

**Review by olamothe — APPROVED** [review]

**Review by nathanlb — APPROVED** [review]
Seems to have worked so here's a thumbs up for you: 👍!
Thanks for making this change in Quantic as well!

**Review by btaillon — APPROVED** [review]

**Pull request merged**
