### PR TITLE
docs(atomic): load default component story when none is specified in URL or specified story isn't found

### PR DESCRIPTION
**Pull request by fbeaudoincoveo**
🧟‍♂️

### CODE REVIEW

**Comment by louis-bompart** [comment]
it works, is there drawbacks?

**Comment by fbeaudoincoveo** [comment]
@srosenberg-coveo / @npushkarskii , the path to the default story will now always be:

`?path=/story/{atomic-component-tag}--default` (where `{atomic-component-tag}` must be substituted).

E.g., 

`?path=/story/atomic-folded-result-list--default`

**Comment by fbeaudoincoveo** [comment]
> it works, any drawbacks? (other than 'gosh darn it's silly we have to do that)

I did notice that if you don't specify a story at all in the `path` query parameter (e.g., if you do `?path=atomic-search-box` instead of `?path=atomic-search-box--whatever`, the Storybook error message saying that the story can't be found will show up for an instant, and then the router will redirect to the default story.

This is still infinitely better than the current state of things, though (which is that it basically never loads the default example, unless, for some obsure reason, the component's PascalCase name only contains a single word, such as Icon or Breadbox).

**Review by louis-bompart — APPROVED** [review]

**Comment by npushkarskii** [comment]
> @srosenberg-coveo / @npushkarskii , the path to the default story will now always be:
> 
> `?path=/story/{atomic-component-tag}--default` (where `{atomic-component-tag}` must be substituted).
> 
> E.g.,
> 
> `?path=/story/atomic-folded-result-list--default`
> 
> You can update the templates in the docs site to avoid flickering, but it should work out of the box once the fix gets deployed.

you're the best, Fred! Thx a lot. @fbeaudoincoveo 

A question: do all components have `atomic-` at the beginning of their tags(names) ? I'm just concerned whether the substitution part is unified on Storybook's end 🤔

\+ @srosenberg-coveo

**Pull request merged**
