### PR TITLE
fix(headless): fetch event source library patched to support working in SF Locker Service

### PR DESCRIPTION
**Pull request by mmitiche**
[SFINT-5159](https://coveord.atlassian.net/browse/SFINT-5159)
fetchEventSource library patched in order to support working in Salesforce Locker Service.

The `AbortController` used by the library can't be used in Salesforce Locker Service, that's why we are creating this patch that will update the usage of this AbortController in the library and allow the GenAi feature to work as expected in Quantic.

to patch this library I used the library: [patch-package](https://www.npmjs.com/package/patch-package?activeTab=readme
)

[SFINT-5159]: https://coveord.atlassian.net/browse/SFINT-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by louis-bompart — CHANGES_REQUESTED** [review]
Additionally:
The solution proposed noop the abort controller, which may impact the functionality of the fetch-event-source packaged.
The AbortController should instead be po*n*yfill (polyfill ain't possible with Locker afaik, pony should be OK tho)

**Comment by erocheleau** [comment]
> Additionally: The solution proposed noop the abort controller, which may impact the functionality of the fetch-event-source packaged. The AbortController should instead be po_n_yfill (polyfill ain't possible with Locker afaik, pony should be OK tho)

The proposed change doesn't noop the `AbortController`, it only makes the library used for EventSource still work when the `AbortController` is not available.

As you can see, this is the main line that changes:

`curRequestController = typeof AbortController === 'undefined' ? null : new AbortController();` 

So this change will have no effect whatsoever whenever the AbortController is actually available aka outside of Locker.

This is our way of making a change that only impacts Locker users and not anything else in other environments.
If you have a better solution, I welcome the suggestions, but this is time sensitive too, we have two different people waiting on this fix. And we couldn't find a better solution.

(We tried using a polyfill, but it breaks the usage of the AbortController in headless. And I don't see how we could ponyfill it for the lib only when the null tolerance behavior is already what is used in the rest of headless.)

**Review by erocheleau — APPROVED** [review]

**Comment by louis-bompart** [comment]
> The proposed change doesn't noop the AbortController, it only makes the library used for EventSource still work when the AbortController is not available.

As it is set to null, it is effectively nooped IMO. In Headless we did measure the impact and adapted our code to use or not use an AbortController with a ponyfill.

We did not conceive the library there, and my concern is: does the library work as intended if we noop the AbortController?

If it works as intended, then the "noop ponyfill" (i.e. if API unavailable, then ignore) is OK. If not, a true ponyfill that replicate the AbortController API would be required.

**Comment by louis-bompart** [comment]
@mmitiche https://github.com/coveo/ui-kit/pull/3126
Should do the same but only impact Quantic build artifacts.
There's some issue with the build process on Windows, so I was not able to confirm that the Quantic build artifacts were properly cleaned up tho.

**Comment by mmitiche** [comment]
> @mmitiche #3126 Should do the same but only impact Quantic build artifacts. There's some issue with the build process on Windows, so I was not able to confirm that the Quantic build artifacts were properly cleaned up tho.

I will test this on my end, thank you!

**Review by louis-bompart — APPROVED** [review]
LGTM with ifs:
 1. If fetch-event-source worked despite the noop of the AbortController
 2. If #3126 build artifacts are the same as this PR, please merge #3126 in there and LGTM, otherwise, assuming 1 is OK, :shipit:

**Pull request merged**
