### PR TITLE
feat(quantic): added focus indicator for facet addMore addLess buttons.

### PR DESCRIPTION
**Pull request by MSLI-Coveo**
[SVCC-2302](https://coveord.atlassian.net/browse/SVCC-2302)
Removed `outline : 0` in order to display borders when `focus-visible` is active
After the changes:
Screen Shot 2022-08-16 at 2 03 16 PM

[SVCC-2381](https://coveord.atlassian.net/browse/SVCC-2381)
Removed `outline : 0` in order to display borders when `focus-visible` is active
Screen Shot 2022-08-17 at 3 41 56 PM

[SVCC-2309](https://coveord.atlassian.net/browse/SVCC-2309)

### CODE REVIEW

**Review by btaillon — APPROVED** [review]
very good!

**Comment by erocheleau** [comment]
We're going to need screenshots for a before/after of the facets more/less buttons.

**Review by erocheleau — COMMENTED** [review]
We'll need screenshot before I can approve this :)

**Review by lbergeron — APPROVED** [review]

**Comment by lbergeron** [comment]
The outline around the "Clear filter" button is uneven. It would be nice to have the outline match the size of the button.

**Pull request merged**
