### PR TITLE
fix(atomic): accessibility issues on "More" tab list

### PR DESCRIPTION
**Pull request by fpbrault**
This PR ensures that the "More" tab list of atomic-tab-manager follows accessibility best practices.
It implements this pattern:
https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/

It also fixes the same issue for the insight panel tabs since they use tab-popover too.

https://coveord.atlassian.net/browse/KIT-3778

### CODE REVIEW

**Review by louis-bompart — APPROVED** [review]

**Comment by fpbrault** [comment]
> Can you explain "why/how" this fixes the issue described in the ticket? 🤔 I understand that it does fix it, but I'm curious to understand how you reached this conclusion fix 🍿

@louis-bompart regarding the count aspect specifically, I first attempted using the menubar pattern, as the menu/menuitems roles is one way to have screenreader announce the count of items in a list. However, I ended up going for the disclosure pattern, (with ul/li) as it is a better fit than the menubar pattern in this scenario:
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/

Additionally, it matches the existing behaviour of insight panel tabs closely, the main difference being is that what happens when pressing tab on the last button in the menu. This is not a modal so focus should not be trapped in the menu.

**Review by alexprudhomme — APPROVED** [review]

**Comment by lvu285** [comment]
@fpbrault nice thanks! It would be great if you can use any screen reader tool to test it also. I know MacBook has some integrated features for that. Otherwise, you can use NVDA or JAWS.

**Comment by fpbrault** [comment]
> @fpbrault nice thanks! It would be great if you can use any screen reader tool to test it also. I know MacBook has some integrated features for that. Otherwise, you can use NVDA or JAWS.

@lvu285 already did with Voiceover utility, works very nicely

**Comment by lvu285** [comment]
@fpbrault genial, merci bcp!
> > @fpbrault nice thanks! It would be great if you can use any screen reader tool to test it also. I know MacBook has some integrated features for that. Otherwise, you can use NVDA or JAWS.
> 
> @lvu285 already did with Voiceover utility, works very nicely

**Review by dmgauthier — APPROVED** [review]

**Pull request merged**
