### PR TITLE
docs(atomic,quantic): DOC-12878-drop-down-to-dropdown

### PR DESCRIPTION
**Pull request by ksampsoncoveo**
Per the Microsoft style guide, we should write dropdown, and not drop-down. 
See https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dropdown.

### CODE REVIEW

**Review by npushkarskii — APPROVED** [review]
Thx a lot, Kevin!

**Review by jpmarceau — APPROVED** [review]
Looks great 👌 
To be able to merge Kevin (actually, I think someone from the ui-kit team has to merge this anyway, but), you need to change the title to `docs(atomic,quantic): DOC-12878...` because their CI/CD pipeline checks for the kind of change in the PR title 🙂

**Review by mmitiche — APPROVED** [review]

**Comment by ksampsoncoveo** [comment]
Can someone merge that PR for me? Thanks!

**Comment by louis-bompart** [comment]
@ksampsoncoveo you should now be able to merge :)

**Comment by jpmarceau** [comment]
@ksampsoncoveo  isn't in the API writer group to which you just granted the permission to merge @louis-bompart , but I am so I'll take care of it 😄

**Pull request merged**
