### PR TITLE
fix: remove pageId from analyticsPayload

### PR DESCRIPTION
**Pull request by louis-bompart**
https://coveord.atlassian.net/browse/KIT-3386

### CODE REVIEW

**Review by alexprudhomme — APPROVED** [review]

**Comment by lvu285** [comment]
@louis-bompart if we remove this one, how it will affect InsightPanel & IPX, as I see the analytics from those products send pageId?

**Comment by louis-bompart** [comment]
> @louis-bompart if we remove this one, how it will affect InsightPanel & IPX, as I see the analytics from those products send pageId?

We have 2 central place where we build the common analytics section for every and any search calls.
Here, where I did the change, and the legacy counterpart, for coveoua.

So, tldr, the change should propagate everywhere :tm:

**Comment by louis-bompart** [comment]
Manually tested:
 - Open ipx.html on localhost.
 - Click a result
 - Do a search
 - Check the analytics part of the search payload
 - Without changes: pageId is in there. With my changes, pageId isn't here.

**Comment by louis-bompart** [comment]
There's concern that it might impact IPX.
As far as we know, IPX is not used/ready to be used with the Event Protocol.

If the pageId is required for a use case, the lob owner/developer should first ensure the schema of existing events (or new events) fit their needs, then trickle it down to the implementation.

From the headless/atomic perspective, The Schema is the sole truth.

**Review by fbeaudoincoveo — APPROVED** [review]

**Review by dguerinCoveo — APPROVED** [review]
We don't specifically use `pageId` anywhere in the code, so no problem for us there. Though I am wondering if this will affect the analytics reports of customer using the old analytics. Is it possible that they have some reporting based on the `pageId`, which will no longer be accessible?

**Pull request merged**
