### PR TITLE
feat(commerce ssr): add method to set view context dynamically

### PR DESCRIPTION
**Pull request by olamothe**
This is needed to allow implementers to set the "view context" (ie: the URL) dynamically, instead of a static definition.

For example, this allow to set something like this statically in a file (ie: `engine-definition.ts`)

```ts
export const commerceEngineDefinition = defineCommerceEngine({
  configuration: {
    // [...]
    context: {
      // [...]
      view: {
        url: `https://sports-dev.barca.group`,
      },
    },
    // [...]
});
```

And then in a listing page, dynamically set the view with something like this: 

```ts
export default async function ProductListingPage() {
 // [...]
  const currentURL = useRouter().pathname;
   commerceEngineDefinitiion.setView({url: currentURL});
   const staticState = await commerceEngineDefinition.listingEngineDefinition.fetchStaticState();

   // [...]
})
```

KIT-3496

### CODE REVIEW

**Review by Spuffynism — APPROVED** [review]
Why is this needed on the engine? Or, put an other way, why is the context controller not enough?

**Comment by olamothe** [comment]
> Why is this needed on the engine? Or, put an other way, why is the context controller not enough?

The way the `defineCommerceEngine` function works (the function used to define the engine for SSR), you cannot "dynamically" modify controllers after the initial definition. 

So you could `defineContext({view: {url: 'something'})` once "statically" but you could not redefine the context again / override the controller with a new value once this is done (right @y-lakhdar ?)

And for ease of use, it's nice for an implementer to have one single static definition in a single file that you re-use everywhere in your project, but then want to "tweak" the definition for a given page.

**Comment by fbeaudoincoveo** [comment]
> Why is this needed on the engine? Or, put an other way, why is the context controller not enough?

This was also my knee jerk reaction, but after doing some local testing, I can't think of a way to effectively use the `Context` controller in an SSR scenario, at least for the purpose of setting the `view.url`.

In order to be able to call the `setView` method on the `Context` controller, we'd have to wait for the hydrated state, which means that the product list we initially render from the static state would not be the correct one (unless the current URL matches the one that was set in the engine's configuration).

Thus we have to be able to set the `view.url` _before_ we fetch the static state.

Going further, this makes me wonder if the `Context` controller is of any use at all in an SSR scenario. Let's take the `currency` property, for example. Suppose we set it to `USD` in the engine's static configuration and use the `Context` controller's `setCurrency` method to update it to the correct value when a user requests the page. When a Canadian user requests the page, the initially rendered page will be in USD, and will get updated to CAD when the state gets hydrated. The same logic applies to `country` and `language`.

**Comment by olamothe** [comment]
After discussion with Fred, I think maybe this could be done instead with "best practice" by telling people to always define the engine dynamically with a builder function in their project....

**Pull request closed without merging**
