### PR TITLE
feat(atomic): disableSearch prop for search box

### PR DESCRIPTION
**Pull request by ThibodeauJF**
https://coveord.atlassian.net/browse/KIT-1765
We're not changing anything to the OOT behaviour. This is just to allow developers to externally prevent users from triggering searches for X condition

### CODE REVIEW

**Review by btaillon — APPROVED** [review]

**Review by olamothe — COMMENTED** [review]
Shouldn't this be a global prop, on the search interface ?

I'm thinking the more generic use case is wanting to stop all searches from being executed, not only those originating from the search box.

**Comment by ThibodeauJF** [comment]
Hmm I could make this a prop on the interface & add it to the store so other component can use it.

But it would take a lot of work to adapt all components that trigger searches to be disabled...

Also, would there be an easy way to disable searches in headless at large?

**Comment by mbenkirane-coveo** [comment]
> https://coveord.atlassian.net/browse/KIT-1765

Which other components trigger searches other than the searchbox and facets? If we don't want a facet to trigger a search the user would just hide it, no?

**Comment by ThibodeauJF** [comment]
Yes it's my original though too, mostly only the search box would need to be visible & interactive while preventing searches altogether

We can also keep this as a search box only prop from the time being, and if we make it general to the whole interface, we can deprecate the prop

**Comment by mbenkirane-coveo** [comment]
> Yes it's my original though too, mostly only the search box would need to be visible & interactive while preventing searches altogether
> 
> We can also keep this as a search box only prop from the time being, and if we make it general to the whole interface, we can deprecate the prop

Sounds like a plan

**Pull request merged**
