### PR TITLE
chore: update sfdx cli

### PR DESCRIPTION
**Pull request by mrrajamanickam-coveo**
5 critical security alerts will be fixed by updating the dev dep of sfdx-cli to latest version (same major).

TODO:

- [ ] Resolve [Setup e2e tests on Quantic](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#logs) fails with `npm ERR! could not determine executable to run`

https://coveord.atlassian.net/browse/KIT-2512

### CODE REVIEW

**Comment by mrrajamanickam-coveo** [comment]
@erocheleau FYI - let me know if there is any specific reason to stick to the older sfdx cli version

**Comment by mrrajamanickam-coveo** [comment]
[Setup e2e tests on Quantic](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#logs) fails with `npm ERR! could not determine executable to run`

```
Prepare all required actions
Getting action download info
Run ./.github/actions/e2e-quantic-setup
Run echo "***
  echo "***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***" > server.key
  npx --no-install sfdx force:auth:jwt:grant \
    --clientid *** \
    --jwtkeyfile server.key \
    --username rdaccess@coveo.com \
    --instanceurl https://login.salesforce.com \
    --setdefaultdevhubusername
  npx --no-install ts-node scripts/build/deploy-community.ts --ci
  rm server.key
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BRANCH_NAME: refs/pull/2952/merge
    SFDX_AUTH_CLIENT_ID: ***
    SFDX_AUTH_JWT_KEY: ***
    SFDX_AUTH_JWT_USERNAME: rdaccess@coveo.com
    SFDX_AUTH_JWT_INSTANCE_URL: https://login.salesforce.com
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-05-3[1](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:1)T[2](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:2)0_[3](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:3)3_4[8](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:9)_[11](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:12)3Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by btaillon** [comment]
> [Setup e2e tests on Quantic](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#logs) fails with `npm ERR! could not determine executable to run`
> 
> ```
> Prepare all required actions
> Getting action download info
> Run ./.github/actions/e2e-quantic-setup
> Run echo "***
>   echo "***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***
>   ***" > server.key
>   npx --no-install sfdx force:auth:jwt:grant \
>     --clientid *** \
>     --jwtkeyfile server.key \
>     --username rdaccess@coveo.com \
>     --instanceurl https://login.salesforce.com \
>     --setdefaultdevhubusername
>   npx --no-install ts-node scripts/build/deploy-community.ts --ci
>   rm server.key
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>   env:
>     BRANCH_NAME: refs/pull/2952/merge
>     SFDX_AUTH_CLIENT_ID: ***
>     SFDX_AUTH_JWT_KEY: ***
>     SFDX_AUTH_JWT_USERNAME: rdaccess@coveo.com
>     SFDX_AUTH_JWT_INSTANCE_URL: https://login.salesforce.com
> npm ERR! could not determine executable to run
> 
> npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-05-3[1](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:1)T[2](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:2)0_[3](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:3)3_4[8](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:9)_[11](https://github.com/coveo/ui-kit/actions/runs/5137311925/jobs/9245464514?pr=2952#step:4:12)3Z-debug-0.log
> Error: Process completed with exit code 1.
> ```

Small chance this could be related to the `overrides` in the root `package.json`.

**Review by btaillon — APPROVED** [review]

**Review by y-lakhdar — APPROVED** [review]

**Comment by mrrajamanickam-coveo** [comment]
> we don't package sfdx-cli so it's a dev dep vulnerability, safe to ignore

**Pull request closed without merging**
