### PR TITLE
fix(atomic): removed dompurify

### PR DESCRIPTION
**Pull request by btaillon**
https://coveord.atlassian.net/browse/KIT-907

Removing `dompurify` reduces the bundle size from ~~1,546,242 bytes~~ 287.4 KiB to ~~1,528,240 bytes~~ 280.8 KiB (~~18 kilobytes~~ 6.6 KiB difference, ~~1.16%~~ 2.3% decrease in bundle size). However, it introduces two potential XSS vulnerabilities through the `icon` prop, as you can see in the removed cypress tests.

Do you think we should remove it or keep it?

### CODE REVIEW

**Comment by ThibodeauJF** [comment]
It's supposed to be treeshakable 🤔  If we don't use the atomic-icon component, it should not increase it? I guess we should check the size of the requested atomic component.

Also a prop is not a shareable user input, but more of a dev configuration, a dev could put any malicious content in the page already.

**Review by ThibodeauJF — APPROVED** [review]

**Comment by samisayegh** [comment]
The 18kb savings is nice, but avoiding XSS is also important. Are you sure about the % savings though? I don't think Atomic's bundle size is `1.5 mb`?

**Comment by olamothe** [comment]
1.5mb is probably wrong indeed. It must be the "dev bundle" you are looking at, which duplicate tailwind and every component.

This is all "cleaned up" in production mode.

**Comment by btaillon** [comment]
@ThibodeauJF @samisayegh @olamothe I tested the bundle sizes, this time by running Chrome's Lighthouse on `v1.html` (both tests with the most recent changes from `master`). The percentage difference is even larger than the first test.

> but avoiding XSS is also important

I'm not entirely sure if this XSS is dangerous since, as JF pointed out, it's only in a prop. Perhaps we could just include a warning in the prop's jsdoc that it isn't protected against XSS. I don't mind the increase in bundle size and small loss in performance for the sake of keeping the prop safe though.

**Comment by olamothe** [comment]
I would personally vote to leave dompurify there.

**Pull request closed without merging**
